name: test-1-generate

permissions:
    contents: write

on:
    workflow_dispatch:
        inputs:
            target_lang:
                description: 'targeted client language'
                required: true
                type: choice
                options:
                    - R
                    - python

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build client
              uses: guilhemheinrich/test-autogen-appeau@main
              with:
                targeted_language: python
                openAPI_description_path: swagger_docs_appeau.json
                destination_path: python_client
            - name: Commit files
              run: |
                git config --local user.email "zezongo@gmail.com"
                git config --local user.name "guilhemheinrich"
                git commit -a -m "[Automated] Updated minor version"
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}
            
